# Generated by Django 4.2 on 2023-05-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_form_remove_product_product_name_product_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
